namespace: kube-system #csi-driver-nfs

#resources:
#  - ../base/

helmCharts:
- name: csi-driver-nfs
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  version: 4.9.0
  releaseName: csi-driver-nfs
  #namespace: csi-driver-nfs
  valuesFile: values.yaml
  includeCRDs: true
